version: "3"
services:
  mysql:
    image: mariadb:10.5.8
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
        - mysql:mysql
    ports:
        - 8080:80
    environment:
        PMA_HOST: mysql
    networks:
      - net-myadmin
      - net-mysql

  redis:
    image: redis:${REDIS_VERION}
    container_name: redis
    hostname: redis
    networks:
      - net-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - net-rabbitmq

  php-redis-admin:
    image: faktiva/php-redis-admin
    container_name: redis-admin
    environment:
        - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        #admin/admin
    ports:
        - "63791:80"
    networks:
        - net-redis
    depends_on:
        - redis
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mango/data/db:/data/db
    ports:
        - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo:mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    depends_on:
      - mongo

  node:
    build: "./nodejs"
    container_name: node
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs/app/:/app:rw
    command: bash -c "npm run start"

  springboot:
    build: "./springboot"
    container_name: springboot
    ports:
      - "8888:8888"
    links:
      - mysql:mysql
    volumes:
      - ./springboot/app:/app:rw
      - ~/.m2:/root/.m2:rw
    networks:
      - net-springboot
      - net-mysql

  etcd1:
    image: "quay.io/coreos/etcd:v3.4.7"
    entrypoint: /usr/local/bin/etcd
    container_name: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
    command:
      - '--initial-cluster-token=etcd-cluster-1'
      - '--initial-cluster=etcd1=http://0.0.0.0:2380'
      - '--initial-cluster-state=new'
      - '--name=etcd1'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd1:2379'
    ports:
      - "2379:2379"
    volumes:
      - ./etcd/store/data:/etcd_data
    networks:
      - net-etcd

  etcdm:
    hostname: etcdm
    image: "shiguanghuxian/etcd-manage:1"
    volumes:
      - ./etcd/bin/config/cfg.toml:/app/config/cfg.toml
      - ./etcd/bin/logs:/app/logs
    ports:
      - "10280:10280"
    networks:
      - net-etcd

  andy-rpc:
    image: "dev-user-rpc:v1"
    container_name: dev-user-rpc
    ports:
      - "9999:9999"
    networks:
      - net-etcd
      - net-mysql
      - net-redis

  andy-api:
    image: "dev-user-api:v1"
    container_name: dev-user-api
    ports:
      - "8888:8888"
    networks:
      - net-etcd
      - net-mysql
      - net-redis

networks:
  net-php:
  net-mysql:
  net-redis:
  net-myadmin:
  net-rabbitmq:
  net-springboot:
  net-etcd:
  net-mongo-express:
  net-mongo:
  net-composer:
